bindsym $mod+apostrophe exec makoctl restore
bindsym $mod+comma exec makoctl dismiss
bindsym $mod+period exec mako-dismiss
bindsym $mod+Shift+period exec makoctl dismiss -a
bindsym $mod+Shift+apostrophe exec mako-toggle-dnd
