# Import the most important environment variables into the D-Bus and systemd user environments
# (e.g. required for screen sharing and Pinentry prompts):
exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_SESSION_TYPE XDG_CURRENT_DESKTOP SSH_AUTH_SOCK
# enable systemd-integration
exec "systemctl --user import-environment {,WAYLAND_}DISPLAY SWAYSOCK XDG_SESSION_TYPE XDG_CURRENT_DESKTOP SSH_AUTH_SOCK; systemctl --user start sway-session.target"
exec "swaymsg -t subscribe '[]'; systemctl --user stop sway-session.target"
