input type:keyboard {
  xkb_layout us
  xkb_options grp:shifts_toggle,ctrl:nocaps,compose:rctrl
  xkb_variant dvorak
}

input 2:10:TPPS/2_Elan_TrackPoint {
   accel_profile adaptive
   pointer_accel -0.25
}
