---
name: Flake Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            trusted-users = root runner
            access-tokens = github.com=${{ secrets.KRYPTONIX_ACCESS_TOKEN }}
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run devenv test
        run: nix develop --no-pure-eval --command devenv test
      - name: Run flake check
        run: nix flake check --no-pure-eval
